kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/pablopaniagua1/demotechsummit.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: demotechsummit-git
  namespace: demotechsummit
  labels:
    app: demotechsummit-git
    app.kubernetes.io/component: demotechsummit-git
    app.kubernetes.io/instance: demotechsummit-git
    app.kubernetes.io/name: httpd
    app.kubernetes.io/part-of: demotechsummit-git-app
    app.openshift.io/runtime: httpd
    app.openshift.io/runtime-version: 2.4-el7
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'demotechsummit-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'httpd:2.4-el7'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/pablopaniagua1/demotechsummit.git'
    contextDir: /
  triggers:
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/httpd@sha256:ff0e23e9f85170a80b6e9755cecad5d06d3fc9e17a4fae6ba7982923aa6b4d45
    - type: ConfigChange
  runPolicy: Serial

